import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from '@/components/navbar';
import About from '@/sections/about';
import Programming from '@/sections/programming';
import Design from '@/sections/design';
import Contact from '@/sections/contact';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hojoon Kim // Design-Centered Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="top-container flex column center">
        <About />
        <Programming />
        <Design />
        <Contact />
      </div>
    </>
  );
}
